### ISSUE TITLE
Unable to resolve service for IDiscordClientWrapper while attempting to activate LavalinkCluster.

### ISSUE THREAD

**Issue by Whatareyoulaughingat** [angelobreuer/Lavalink4NET#74]
An exception is thrown when attempting to activate the LavalinkCluster class using dependency injection.

How to reproduce:
1. Install the latest version (Currently it's 1.7.0).
2. Replace IDiscordClientWrapper with DiscordClientWrapperBase in a .AddSingletion().
3. Use LavalinkCluster in another .AddSingletion().
4. Run the application.

I expected everything would go smoothly but it seems that the LavalinkCluster class implements IDiscordClientWrapper inside its constructor. Maybe replacing IDiscordClientWrapper with the new DiscordClientWrapperBase class and making the appropriate changes will make everything work again.

 - Lavalink4NET Version 1.7.0
 - Exception thrown: Unable to resolve service for type 'Lavalink4NET.IDiscordClientWrapper' while attempting to activate 'Lavalink4NET.Cluster.LavalinkCluster'.
 
![Capture](https://user-images.githubusercontent.com/66755323/116317802-83b06d80-a7bc-11eb-9637-1bd5b356f002.PNG)
![Capture1](https://user-images.githubusercontent.com/66755323/116317835-8e6b0280-a7bc-11eb-8684-3fccd0d6bc99.PNG)

**Comment by angelobreuer** [comment]
Is there a reason why you use `DiscordClientWrapperBase` over `IDiscordClientWrapper`, it should work as expected when you use the interface. In DI it is more common to use interfaces instead of abstract types. 

Adding the `DiscordClientWrapperBase` as an overload to the cluster constructors would need to add `Lavalink4NET.DSharpPlus` as a dependency of `Lavalink4NET` which would exactly do the opposite of the reason to have the `IDiscordClientWrapper` interface.

Lavalink4NET is designed to have the same API regardless of whether you use DSharpPlus, Discord.Net or any of the others.

**Comment by Whatareyoulaughingat** [comment]
Correct me if i am doing something wrong, but this what happens when i use IDiscordClientWrapper.

![Capture1](https://user-images.githubusercontent.com/66755323/116319754-bf990200-a7bf-11eb-97f3-88bb61d0c7db.PNG)
![Capture](https://user-images.githubusercontent.com/66755323/116319755-c0319880-a7bf-11eb-8646-140ff59abc98.PNG)

**Comment by angelobreuer** [comment]
Oh, I see. I think I missed the interface implementation on the base class. Give me some time to deploy a fix

**Comment by angelobreuer** [comment]
Could you try out Lavalink4NET 1.7.1? I think it should work now, I added the interface in https://github.com/angelobreuer/Lavalink4NET/commit/b28124d84d0deedf4d1028e7980c383db2f03d1d .

**Comment by Whatareyoulaughingat** [comment]
Same problem again with the same exception. By the way, i still have the client wrapper from the previous bug report and it still works great. It inherits only from IDiscordClientWrapper, so i don't think there will be any problems.
